blank_issues_enabled: false
contact_links:
  - name: 💬 Discord server
    url: https://discord.gg/mhxsSMy2Nf
    about: Chat with the project community.

  - name: Support
    url: https://www.buymeacoffee.com/jerry08
    about: Support the developer.